[lab]
name = "local"
hostname = "localhost"
user = "hws"
keyfile = "/home/hws/.ssh/id_rsa"
# password = "hunter2"

[tbot]
workdir = "/home/hws/tbotdir"

[tftp]
rootdir = "/tmp/tftp"
tbotsubdir = "tbot"

[uboot]
repository = "git://git.denx.de/u-boot.git"
test_use_venv = true

[toolchains."cortexa8hf-neon"]
path = "/home/hws/Documents/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi"
env_setup_script = "/home/hws/Documents/sdk/environment-setup-cortexa8hf-neon-poky-linux-gnueabi"
prefix = "arm-poky-linux-gnueabi-"
