# TODO: Move to new format
[board]
name = "at91sam9g45"
toolchain = "cortexa8hf-neon"
defconfig = "corvus_defconfig"

[board.power]
on_command = "remote_power at91sam9g45 on"
off_command = "remote_power at91sam9g45 off"

[board.shell]
name = "connect_at91sam9g45"
command = "connect at91sam9g45"
prompt = "U-Boot> "

[uboot]
patchdir = "/home/hws/corvus_patches"
test_hooks = "/home/hws/hooks/corvus"
test_boardname = "corvus"

[tftp]
boarddir = "at91sam9g45"
