[board]
name = "at91_taurus"
toolchain = "generic-armv7a-hf"
defconfig = "taurus_defconfig"

[uboot]
patchdir = "/work/hs/tbot/patches/taurus_uboot_patches"
env_location = "/home/hws/env/taurus-env.txt"

[tftp]
boarddir = "at91_taurus"
