name: Deploy tbot documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Deploy to GH-Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies, linters, doc-tools
        run: |
          python -m pip install --upgrade pip
          pip install recommonmark sphinx sphinx_rtd_theme
          pip install termcolor2 pyserial paramiko
      - name: Build documentation
        run: |
          ./Documentation/build-docs.sh
          rm -r Documentation/output/.doctrees
          touch Documentation/output/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Documentation/output
          publish_branch: gh-pages
          cname: tbot.tools
          force_orphan: true
